package com.comtab.model;
// Generated Oct 17, 2013 7:06:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Giohang generated by hbm2java
 */
@Entity
@Table(name = "cart")
public class Cart {

	@Id
     private int id;
    @ManyToOne
 	@JoinColumn(name = "usernamecus", referencedColumnName = "username")
     private Customer customer;
     private String createdDay;
    @OneToMany(mappedBy = "cart", fetch = FetchType.LAZY)
     private Set<CartDetail> cartDetail = new HashSet(0);

    public Cart() {
    }

	public Cart(int id, Customer customer, String createdDay,
			Set<CartDetail> cartDetail) {
		super();
		this.id = id;
		this.customer = customer;
		this.createdDay = createdDay;
		this.cartDetail = cartDetail;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getCreatedDay() {
		return createdDay;
	}

	public void setCreatedDay(String createdDay) {
		this.createdDay = createdDay;
	}

	public Set<CartDetail> getCartDetail() {
		return cartDetail;
	}

	public void setCartDetail(Set<CartDetail> cartDetail) {
		this.cartDetail = cartDetail;
	}

	
    

}


