package com.comtab.model;
// Generated Oct 17, 2013 7:06:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name = "product")
public class Product {
	
	@Id
     private String id;
	@ManyToOne
	@JoinColumn(name = "brandid", referencedColumnName = "id")
     private Brand brand;
     private String name;
     private String color;
     private double price;
     private double size;
     private Integer amount;
     private String type;
     private String picture;
     @OneToMany(mappedBy = "product", fetch = FetchType.LAZY)
     private Set<CartDetail> cartDetail = new HashSet(0);

    public Product() {
    }
    
	public Product(String id) {
		super();
		this.id = id;
	}
			

	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	
	public Brand getBrand() {
		return brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getColor() {
		return color;
	}
	public void setColor(String color) {
		this.color = color;
	}
	
	public Double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Double getSize() {
		return size;
	}

	public void setSize(double size) {
		this.size = size;
	}

	public Integer getAmount() {
		return amount;
	}
	public void setAmount(Integer amount) {
		this.amount = amount;
	}
	
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPicture() {
		return picture;
	}
	public void setPicture(String picture) {
		this.picture = picture;
	}

	public Set<CartDetail> getCartDetail() {
		return cartDetail;
	}

	public void setCartDetail(Set<CartDetail> cartDetail) {
		this.cartDetail = cartDetail;
	}
	
  



}


