package com.comtab.model;
// Generated Oct 17, 2013 7:06:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Giohang generated by hbm2java
 */
@Entity
@Table(name = "saleoff")
public class SaleOff {

	@Id
     private int id;
    @ManyToOne
 	@JoinColumn(name = "productid", referencedColumnName = "id")
     private Product product;
     private double discount;
     
    public SaleOff() {
    }

	public SaleOff(int id, Product product, double discount) {
		super();
		this.id = id;
		this.product = product;
		this.discount = discount;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public double getDiscount() {
		return discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}
    
    
}